Instrucciones para compilar el app del lab9:
Paso 1 instalar las dependencias de streamlit:
pip install streamlit
pip install streamlit pandas plotly scikit-learn
Paso 2 ejecutar el app:
streamlit run App.py
Nota, para ejecutar el app se debe estar en la carpeta lab9:
 


